basic:
  image_tag_version: "sha-7e1b436"
  controller_image_name: "public.ecr.aws/n9u9x7z1/volcano-controller-manager"
  scheduler_image_name: "public.ecr.aws/n9u9x7z1/volcano-scheduler"
  admission_image_name: "public.ecr.aws/n9u9x7z1/volcano-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  admission_config_file: "config/volcano-admission.conf"
  scheduler_config_file: "config/volcano-scheduler.conf"
  image_pull_secret: ""
  admission_port: 8443
custom:
  metrics_enable: false
  admission_enable: true
  controller_enable: true
  scheduler_enable: true
  enabled_admissions: "/jobs/mutate,/jobs/validate,/podgroups/mutate,/pods/validate,/pods/mutate,/queues/mutate,/queues/validate"
