basic:
  image_tag_version: "1.7.0-fix"
  controller_image_name: "volcanosh/vc-controller-manager"
  scheduler_image_name: "474375891613.dkr.ecr.us-west-2.amazonaws.com/volcano"
  admission_image_name: "volcanosh/vc-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  admission_config_file: "config/volcano-admission.conf"
  scheduler_config_file: "config/volcano-scheduler.conf"
  image_pull_secret: ""
  admission_port: 8443
custom:
  metrics_enable: false
  admission_enable: true
  controller_enable: true
  scheduler_enable: true
  enabled_admissions: "/jobs/mutate,/jobs/validate,/podgroups/mutate,/pods/validate,/pods/mutate,/queues/mutate,/queues/validate"
